# Generated by Django 2.2.4 on 2022-02-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='ip')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='region')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='country')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='location')),
                ('organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='organization')),
                ('timezone', models.CharField(blank=True, max_length=60, null=True, verbose_name='timezone')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ip data',
                'verbose_name_plural': 'ip data',
                'db_table': 'ip_data',
            },
        ),
    ]
