# Generated by Django 2.2.4 on 2022-02-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdata',
            name='host_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipdata',
            name='postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
