# Generated by Django 2.2.4 on 2022-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_app', '0002_auto_20220227_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdata',
            name='bogon',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
